name: Wayclip Docs Docker Image

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        if: "contains(github.event.head_commit.message, '[DOCS]')"
        runs-on: blacksmith-4vcpu-ubuntu-2404

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Setup Blacksmith Builder
              uses: useblacksmith/setup-docker-builder@v1

            - name: Build and push Docker image
              uses: useblacksmith/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: wayclip/docs:latest
                  platforms: linux/amd64,linux/arm64
